#!/usr/bin/env php
<?php
if (file_exists('../../autoload.php')) {
    // In vendor/twogether/sweet-qa.
    require_once '../../autoload.php';
    chdir(__DIR__);
} elseif (file_exists('../vendor/autoload.php')) {
    // In parent project's bin/.
    require_once '../vendor/autoload.php';
    chdir('../vendor/twogether/sweet-qa');
} elseif (file_exists('vendor/autoload.php')) {
    // In parent project's root/.
    require_once 'vendor/autoload.php';
    chdir('vendor/twogether/sweet-qa');
} else {
    throw new \RuntimeException('Could not find the autoloader.');
}

use Symfony\Component\Console\Application;
use Twogether\SweetQA\Command as Commands;
    
stream_context_set_default([
    'http' => [
        'ignore_errors' => true
    ]
]);

$application = new Application("Sweet QA", "0.0.1-dev");
$application->add(new Commands\TestCommand);
$application->add(new Commands\ExpectationsCommand);
$application->run();
